* All You Can Carry
Een verzameling van nuttige documenten voor het examen van numerieke wiskunde.

** Compileren
    Aan dit project kon helaas geen continuous integration toegevoegd worden.
    Om heel de bundel samen te stellen voer je de volgende procedure uit in je terminal.
    #+BEGIN_EXAMPLE
    git clone https://github.com/NorfairKing/all-you-can-carry.git
    cd all-you-can-carry
    make
    #+END_EXAMPLE
    Na het invoeren van het make commando zie je een gigantische hoeveelheid tekst over je scherm vliegen.
    Vereisten:
      - Latexmk: http://users.phys.psu.edu/~collins/software/latexmk-jcc/
      - pdfunite: Normaal standaard op linux
      - Latex
        - Subfiles

    Het compilatieproces is uitvoerig getest. Enig probleem hiermee is, wel..., uw probleem.

** OPROEP
   Deze repository is _open_. *iedereen* kan iets toevoegen of verbeteren. Dit is dan ook de bedoeling.
   Niet alleen kan je zoals altijd de repository forken en pull requests doen, je kan de repository ook clonen en ernaar pushen.
   Je hoeft dus zelfs geen contributor te zijn.

** De bedoeling
   Deze repository bevat heel veel informatie die het instuderen van numerieke wiskunde zou kunnen vergemakkelijken.
   Omdat het examen openboek is, kan het bovendien van pas komen om sommige van deze documenten af te drukken.

   De bedoeling is dat alle informatie hier wordt gebundeld.
   We stellen alle tex code ter beschikking, zodat er verbeterd en verder aangevuld kan worden.
** Inhoud
    Alle pdf's in deze repository kunnen samengevoegd worden met het make commando.
    Je zal LaTeX, subfiles en latexmk nodig hebben om dit uit te voeren.
    - Samenvatting
    - Oplossingen Oefenzittingen
    - Examenvragen en -antwoorden
    - Tutorials
      - Foutenanalyse
      - Conditie en Stabiliteit
      - Kwadratuurformules  
    - Extraatjes
      - Afgeleiden en integralen
      - Goniometrische cirkel en formules
      - Meer over foutenanalyse
      - QR-factorisatie
      - Splines
    - Oud
      - De originele opgeloste examenvragen van Jonas Devlieghere
      - Een voorbeeldexamen, opgelost door de prof.
    _Neem zeker ook de cursus mee!_
** Examenvragen
   De examenvragen en oplossingen zijn overgenomen en vrij aangepast van volgende uitgave.
   Alle credit voor de originele vragen en antwoorden gaat naar hen.
   https://github.com/JDevlieghere/NumeriekeWiskunde
   Deze uitgave is gelicenseerd met het apache license.
